name: POC CI Auto-created
on:
  workflow_dispatch:
    inputs:
      tcrt_run_id:
        description: 'TCRT correlation ID'
        required: false
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "tcrt_run_id=${{ github.event.inputs.tcrt_run_id }}"
